#!/bin/sh
printf "Content-type: text/html\n\n"

echo "node_uname_info{domainname=\"(none)\",machine=\"$(uname -m)\",nodename=\"$(uci get system.@system[0].hostname)\",release=\"$(uname -r)\",sysname=\"Linux\",version=\"$(uname -v)\"} 1"

for net in /sys/class/net/*; do
   int="$(basename "$net")"
   echo node_network_receive_bytes_total{device=\"$int\"} $(cat /sys/class/net/$int/statistics/rx_bytes)
   echo node_network_transmit_bytes_total{device=\"$int\"} $(cat /sys/class/net/$int/statistics/tx_bytes)
   echo node_network_receive_packets_total{device=\"$int\"} $(cat /sys/class/net/$int/statistics/rx_packets)
   echo node_network_transmit_packets_total{device=\"$int\"} $(cat /sys/class/net/$int/statistics/tx_packets)
   echo node_network_receive_errs_total{device=\"$int\"} $(cat /sys/class/net/$int/statistics/rx_errors)
   echo node_network_transmit_errs_total{device=\"$int\"} $(cat /sys/class/net/$int/statistics/tx_errors)
   echo node_network_receive_drop_total{device=\"$int\"} $(cat /sys/class/net/$int/statistics/rx_dropped)
   echo node_network_transmit_drop_total{device=\"$int\"} $(cat /sys/class/net/$int/statistics/tx_dropped)

  if [ -d "/sys/class/net/$int/wireless" ]; then
     type="$(iw $int info | grep type | awk '{print $2}')"
    mac="$(cat /sys/class/net/$int/address)"
    channel="$(iw $int info | grep channel | awk '{print $2}')"
    if [ -z "$channel" ]; then
       channel=0
    fi
    echo wireless_channel{device=\"$int\",type=\"$type\"} $channel
    for ST in $(iw $int station dump | grep Station  | awk '{print $2}')
    do
      res=$(iw $int station dump | grep -A 15 $ST | grep rx\ bytes | awk '{print $3}')
      echo wireless_link_receive_bytes_total{sourcemac=\"$mac\",device=\"$int\",targetmac=\"$ST\"} $res
      res=$(iw $int station dump | grep -A 15 $ST | grep tx\ bytes | awk '{print $3}')
      echo wireless_link_transmit_bytes_total{sourcemac=\"$mac\",device=\"$int\",targetmac=\"$ST\"} $res
      res=$(iw $int station dump | grep -A 15 $ST | grep signal\: | awk '{print $2}')
      echo wireless_link_receive_signal{sourcemac=\"$mac\",device=\"$int\",targetmac=\"$ST\"} $res
    done
  fi

done
cat /proc/loadavg | awk '{print "node_load1 "$1"\nnode_load5 "$2"\nnode_load15 "$3}'
cat /proc/uptime | awk '{print "node_boot_time_seconds "$1}'
